// <auto-generated />
using System;
using Ecommerce.Server.Entites;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ecommerce.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240707193400_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Ecommerce.Server.Entites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountedPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RatingCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4079),
                            Description = "High-quality portable speaker",
                            DiscountedPrice = 39.00m,
                            ImageUrl = "https://cdn5.425degree.com/media/amasty/webp/wysiwyg/2020/07/Air_by_MPOW_X51J/BnO_A1_Gen2/Beosound_a1_black_hero_jpg.webp",
                            Name = "Beoplay A1",
                            OriginalPrice = 57.00m,
                            Rating = 5,
                            RatingCount = 10,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4088),
                            Vendor = "Bang & Olufsen"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4091),
                            Description = "Comfortable and stylish chair",
                            DiscountedPrice = 40.00m,
                            ImageUrl = "https://artisan-production.ams3.cdn.digitaloceanspaces.com/neva_chair_inspiration_8_6dd1b35090.png",
                            Name = "Artisan Chair",
                            OriginalPrice = 48.00m,
                            Rating = 4,
                            RatingCount = 8,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4091),
                            Vendor = "Artisan"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4093),
                            Description = "Elegant and relaxing hanging chair",
                            DiscountedPrice = 89.00m,
                            ImageUrl = "https://sika-design.com/cdn/shop/products/Hanging_Egg_stand_4957_1200x.jpg?v=1648003559",
                            Name = "Hanging Egg Chair",
                            OriginalPrice = 99.00m,
                            Rating = 5,
                            RatingCount = 12,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4094),
                            Vendor = "Egg Chairs"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Lighting",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4096),
                            Description = "Modern pendant lamp with sleek design",
                            DiscountedPrice = 140.00m,
                            ImageUrl = "https://www.macomaitaly.com/33163-large_default/hubert-pendant-lamp-audo-.jpg",
                            Name = "Hubert Pendant Lamp",
                            OriginalPrice = 149.00m,
                            Rating = 4,
                            RatingCount = 6,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4096),
                            Vendor = "Lighting"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Toys",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4098),
                            Description = "Classic rocking horse for children",
                            DiscountedPrice = 135.00m,
                            ImageUrl = "https://www.designboom.com/wp-content/dbsub/401760/2017-08-17/img_1_1502954593_09c46de59d5651a30e2240ed15335b13.jpg",
                            Name = "Iconic Rocking Horse",
                            OriginalPrice = 150.00m,
                            Rating = 5,
                            RatingCount = 5,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4099),
                            Vendor = "Toys"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4101),
                            Description = "Stackable and versatile chair",
                            DiscountedPrice = 250.00m,
                            ImageUrl = "https://www.eustischair.com/wp-content/uploads/2019/04/Ivy-League-Stackable-M.jpg",
                            Name = "League Stack Chair",
                            OriginalPrice = 290.00m,
                            Rating = 4,
                            RatingCount = 9,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4102),
                            Vendor = "League"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Home Essentials",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4104),
                            Description = "Durable and stylish laundry baskets",
                            DiscountedPrice = 40.00m,
                            ImageUrl = "https://www.ikea.com/th/en/images/products/tolkning-laundry-basket-handmade-willow__1098731_pe865503_s5.jpg?f=s",
                            Name = "Laundry Baskets",
                            OriginalPrice = 45.00m,
                            Rating = 4,
                            RatingCount = 7,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4105),
                            Vendor = "Home Essentials"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Lighting",
                            CreatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4132),
                            Description = "Unique table lamp with mug design",
                            DiscountedPrice = 79.00m,
                            ImageUrl = "https://www.midj.com/images/uploads/products/_xl/mug-table-midj.jpg",
                            Name = "Mug Table Lamp",
                            OriginalPrice = 89.00m,
                            Rating = 5,
                            RatingCount = 11,
                            UpdatedAt = new DateTime(2024, 7, 8, 2, 34, 0, 29, DateTimeKind.Local).AddTicks(4133),
                            Vendor = "Lighting"
                        });
                });

            modelBuilder.Entity("Ecommerce.Server.Entites.SKU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("InStock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("SKUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "B&O-A1-001",
                            InStock = true,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "B&O-A1-002",
                            InStock = false,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "ART-CHAIR-001",
                            InStock = true,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "EGG-CHAIR-001",
                            InStock = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "EGG-CHAIR-002",
                            InStock = true,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "HUB-LAMP-001",
                            InStock = false,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            Code = "TOY-HORSE-001",
                            InStock = true,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            Code = "LEA-CHAIR-001",
                            InStock = true,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 9,
                            Code = "HOME-BASKET-001",
                            InStock = true,
                            ProductId = 7
                        },
                        new
                        {
                            Id = 10,
                            Code = "LAMP-MUG-001",
                            InStock = true,
                            ProductId = 8
                        });
                });

            modelBuilder.Entity("Ecommerce.Server.Entites.SKU", b =>
                {
                    b.HasOne("Ecommerce.Server.Entites.Product", null)
                        .WithMany("SKUs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ecommerce.Server.Entites.Product", b =>
                {
                    b.Navigation("SKUs");
                });
#pragma warning restore 612, 618
        }
    }
}
